### ISSUE TITLE
LB001 Creación de base de datos

### ISSUE THREAD

**Issue by GeraChinchillar** [DianaSanchez1103/LasBichotas_proyecto_SIG_ACA#2]
Objetivo: Creación de base de datos PostgreSQL con los datos obtenidos sobre las fuentes de energía renovable

- [x]  Diagrama entidad-relación
- [x]  Creación del script

**Comment by DianaSanchez1103** [comment]
Creando tabla(s)

**Comment by DianaSanchez1103** [comment]
Agregando datos a la base de datos
